# Starter pipeline with a self-hosted agent

trigger:
- master

pool:
  name: Default  # Ensure this matches your self-hosted agent pool
  demands:
    - agent.name -equals JASHRUTHA  # Ensures the job runs on your agent

steps:
- script: echo Hello, self-hosted agent!
  displayName: 'Run a one-line script on JASHRUTHA'

- task: CmdLine@2
  inputs:
    script: |
      echo Running commands on JASHRUTHA
      echo Hello from the self-hosted agent!
